name: Publish to GitHub Container Registry

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * 3' # Weekly on Wednesday at 04:30

jobs:
  latest-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build latest CLI version and publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: mileschou/xdebug
          tags: "latest,8.4"
          username: mileschou
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: 8.4/Dockerfile

  latest-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build latest Alpine version and publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: mileschou/xdebug
          tags: "alpine,8.4-alpine"
          username: mileschou
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: 8.4/alpine/Dockerfile

  latest-apache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build latest Apache version and publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: mileschou/xdebug
          tags: "apache,8.4-apache"
          username: mileschou
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: 8.4/apache/Dockerfile

  cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - '8.3'
          - '8.2'
          - '8.1'
          - '8.0'
          - '7.4'
          - '7.3'
          - '7.2'
          - '7.1'
          - '7.0'
          - '5.6'
          - '5.5'
    steps:
      - uses: actions/checkout@master
      - name: Build PHP ${{ matrix.version }} CLI and publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: mileschou/xdebug
          tags: ${{ matrix.version }},${{ matrix.version }}-cli
          username: mileschou
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: ${{ matrix.version }}/Dockerfile

  alpine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - '8.3'
          - '8.2'
          - '8.1'
          - '8.0'
          - '7.4'
          - '7.3'
          - '7.2'
          - '7.1'
          - '7.0'
          - '5.6'
          - '5.5'
    steps:
      - uses: actions/checkout@master
      - name: Build PHP ${{ matrix.version }} Alpine and publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: mileschou/xdebug:${{ matrix.version }}-alpine
          username: mileschou
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: ${{ matrix.version }}/alpine/Dockerfile

  apache:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - '8.3'
          - '8.2'
          - '8.1'
          - '8.0'
          - '7.4'
          - '7.3'
          - '7.2'
          - '7.1'
          - '7.0'
          - '5.6'
          - '5.5'
    steps:
      - uses: actions/checkout@master
      - name: Build PHP ${{ matrix.version }} Apache and publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: mileschou/xdebug:${{ matrix.version }}-apache
          username: mileschou
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: ${{ matrix.version }}/apache/Dockerfile
